<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3f18dbc4333575bcddb0c60c6b068853
{
    public static $prefixesPsr0 = array (
        'B' => 
        array (
            'BBMParser' => 
            array (
                0 => __DIR__ . '/..' . '/magrao/bibliomundi-onix-parser/src',
            ),
            'BBM' => 
            array (
                0 => __DIR__ . '/..' . '/magrao/client-side-api/lib',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit3f18dbc4333575bcddb0c60c6b068853::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
