<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'BBMParser' => array($vendorDir . '/magrao/bibliomundi-onix-parser/src'),
    'BBM' => array($vendorDir . '/magrao/client-side-api/lib'),
);
